CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, surname TEXT NOT NULL, age INTEGER, active INTEGER, bio TEXT, score REAL);
CREATE TABLE IF NOT EXISTS products (sku TEXT PRIMARY KEY, name TEXT NOT NULL, price INTEGER, stock INTEGER, category TEXT) WITHOUT ROWID;
CREATE TABLE IF NOT EXISTS orders (order_id INTEGER, item_id INTEGER, quantity INTEGER, total REAL, status TEXT, PRIMARY KEY (order_id, item_id));
INSERT INTO users (id, surname, age, active, bio, score) VALUES (1, 'Alex Smith', 65, 0, 'User 1 bio description', 30.09);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (2, 'Alex Moore', 23, 1, 'User 2 bio description', 12.86);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (3, 'Kiri Miller', 32, 1, 'User 3 bio description', 12.39);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (4, 'Morgan Moore', 44, 0, 'User 4 bio description', 63.03);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (5, 'Amatsagu Garcia', 62, 1, 'User 5 bio description', 35.01);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (6, 'Morgan Hernandez', 24, 0, 'User 6 bio description', 18.7);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (7, 'Casey Martin', 34, 1, 'User 7 bio description', 75.68);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (8, 'Skyler Brown', 80, 1, 'User 8 bio description', 17.09);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (9, 'Pat Martin', 74, 1, 'User 9 bio description', 61.96);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (10, 'Kiri Johnson', 60, 0, 'User 10 bio description', 36.04);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (11, 'Kiri Davis', 73, 0, 'User 11 bio description', 35.02);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (12, 'Casey Garcia', 41, 1, 'User 12 bio description', 70.32);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (13, 'Kiri Martin', 58, 0, 'User 13 bio description', 75.62);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (14, 'Taylor Anderson', 42, 0, 'User 14 bio description', 93.29);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (15, 'Skyler Davis', 61, 1, 'User 15 bio description', 79.15);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (16, 'Betta Davis', 70, 0, 'User 16 bio description', 38.39);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (17, 'Chris Williams', 31, 1, 'User 17 bio description', 61.05);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (18, 'Riley Miller', 59, 1, 'User 18 bio description', 89.62);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (19, 'Dakota Jones', 34, 0, 'User 19 bio description', 77.05);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (20, 'Skyler Rodriguez', 65, 1, 'User 20 bio description', 90.8);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (21, 'Avery Lopez', 32, 1, 'User 21 bio description', 22.45);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (22, 'Reese Williams', 66, 0, 'User 22 bio description', 19.87);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (23, 'Taylor Wilson', 56, 0, 'User 23 bio description', 44.35);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (24, 'Dakota Taylor', 34, 1, 'User 24 bio description', 87.47);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (25, 'Amatsagu Brown', 61, 1, 'User 25 bio description', 77.58);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (26, 'Riley Brown', 36, 1, 'User 26 bio description', 50.84);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (27, 'Chris Taylor', 66, 0, 'User 27 bio description', 92.14);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (28, 'Pat Taylor', 56, 0, 'User 28 bio description', 43.65);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (29, 'Taylor Moore', 79, 1, 'User 29 bio description', 57.73);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (30, 'Amatsagu Martin', 38, 1, 'User 30 bio description', 20.07);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (31, 'Casey Martinez', 33, 0, 'User 31 bio description', 89.02);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (32, 'Kiri Williams', 64, 1, 'User 32 bio description', 16.23);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (33, 'Skyler Jones', 26, 1, 'User 33 bio description', 95.22);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (34, 'Taylor Rodriguez', 51, 1, 'User 34 bio description', 48.08);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (35, 'Morgan Moore', 66, 1, 'User 35 bio description', 28.1);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (36, 'Pat Gonzalez', 60, 1, 'User 36 bio description', 49.43);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (37, 'Quinn Anderson', 25, 0, 'User 37 bio description', 15.76);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (38, 'Amatsagu Jackson', 53, 0, 'User 38 bio description', 29.82);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (39, 'Kiri Johnson', 32, 0, 'User 39 bio description', 12.83);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (40, 'Riley Williams', 50, 0, 'User 40 bio description', 70.21);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (41, 'Morgan Moore', 26, 1, 'User 41 bio description', 89.41);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (42, 'Rowan Thomas', 33, 1, 'User 42 bio description', 82.67);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (43, 'Morgan Brown', 24, 1, 'User 43 bio description', 41.89);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (44, 'Logan Anderson', 73, 1, 'User 44 bio description', 70.6);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (45, 'Alex Johnson', 43, 1, 'User 45 bio description', 82.05);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (46, 'Alex Davis', 30, 0, 'User 46 bio description', 50.38);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (47, 'Logan Garcia', 35, 1, 'User 47 bio description', 88.7);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (48, 'Kiri Anderson', 69, 1, 'User 48 bio description', 59.53);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (49, 'Betta Moore', 71, 0, 'User 49 bio description', 18.39);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (50, 'Sam Garcia', 44, 1, 'User 50 bio description', 29.24);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (51, 'Avery Johnson', 28, 1, 'User 51 bio description', 98.68);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (52, 'Chris Anderson', 36, 1, 'User 52 bio description', 96.16);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (53, 'Skyler Thomas', 27, 0, 'User 53 bio description', 29.59);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (54, 'Betta Jackson', 65, 1, 'User 54 bio description', 77.32);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (55, 'Betta Johnson', 55, 1, 'User 55 bio description', 92.74);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (56, 'Quinn Garcia', 21, 1, 'User 56 bio description', 17.21);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (57, 'Taylor Williams', 56, 0, 'User 57 bio description', 87.56);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (58, 'Avery Brown', 78, 1, 'User 58 bio description', 32.16);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (59, 'Hayden Johnson', 57, 0, 'User 59 bio description', 69.16);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (60, 'Rowan Taylor', 38, 1, 'User 60 bio description', 28.38);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (61, 'Riley Davis', 34, 1, 'User 61 bio description', 70.45);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (62, 'Pat Anderson', 38, 1, 'User 62 bio description', 94.22);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (63, 'Amatsagu Anderson', 57, 1, 'User 63 bio description', 99.65);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (64, 'Kiri Moore', 31, 1, 'User 64 bio description', 21.92);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (65, 'Casey Williams', 74, 0, 'User 65 bio description', 35.65);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (66, 'Dakota Moore', 63, 1, 'User 66 bio description', 98.55);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (67, 'Quinn Smith', 60, 1, 'User 67 bio description', 36.94);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (68, 'Alex Jones', 34, 0, 'User 68 bio description', 19.63);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (69, 'Skyler Jones', 35, 0, 'User 69 bio description', 28.96);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (70, 'Riley Miller', 61, 1, 'User 70 bio description', 33.76);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (71, 'Reese Rodriguez', 75, 1, 'User 71 bio description', 14.57);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (72, 'Logan Rodriguez', 20, 0, 'User 72 bio description', 79.4);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (73, 'Chris Garcia', 65, 1, 'User 73 bio description', 73.51);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (74, 'Skyler Smith', 25, 0, 'User 74 bio description', 89.48);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (75, 'Jordan Moore', 20, 1, 'User 75 bio description', 62.43);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (76, 'Jordan Wilson', 26, 0, 'User 76 bio description', 42.82);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (77, 'Betta Lopez', 31, 1, 'User 77 bio description', 70.02);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (78, 'Casey Moore', 74, 1, 'User 78 bio description', 97.65);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (79, 'Jordan Davis', 73, 0, 'User 79 bio description', 81.99);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (80, 'Taylor Wilson', 19, 0, 'User 80 bio description', 93.2);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (81, 'Logan Davis', 35, 0, 'User 81 bio description', 73.12);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (82, 'Avery Johnson', 72, 1, 'User 82 bio description', 27.96);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (83, 'Dakota Lopez', 37, 1, 'User 83 bio description', 88.42);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (84, 'Sam Smith', 60, 0, 'User 84 bio description', 39.54);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (85, 'Kiri Rodriguez', 40, 1, 'User 85 bio description', 45.97);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (86, 'Skyler Hernandez', 78, 0, 'User 86 bio description', 88.93);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (87, 'Chris Garcia', 55, 1, 'User 87 bio description', 33.89);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (88, 'Alex Martin', 45, 1, 'User 88 bio description', 80.78);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (89, 'Logan Martin', 80, 1, 'User 89 bio description', 44.67);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (90, 'Rowan Miller', 34, 0, 'User 90 bio description', 49.25);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (91, 'Quinn Moore', 61, 1, 'User 91 bio description', 76.78);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (92, 'Morgan Lopez', 45, 0, 'User 92 bio description', 69.78);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (93, 'Riley Martin', 38, 1, 'User 93 bio description', 21.22);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (94, 'Pat Taylor', 37, 1, 'User 94 bio description', 39.36);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (95, 'Pat Moore', 26, 0, 'User 95 bio description', 69.84);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (96, 'Avery Garcia', 57, 1, 'User 96 bio description', 46.55);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (97, 'Amatsagu Martinez', 36, 0, 'User 97 bio description', 80.72);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (98, 'Hayden Hernandez', 47, 1, 'User 98 bio description', 70.81);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (99, 'Quinn Thomas', 68, 1, 'User 99 bio description', 81.64);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (100, 'Taylor Williams', 36, 1, 'User 100 bio description', 66.96);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (101, 'Riley Williams', 70, 1, 'User 101 bio description', 31.14);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (102, 'Pat Davis', 69, 0, 'User 102 bio description', 12.2);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (103, 'Sam Thomas', 57, 1, 'User 103 bio description', 16.55);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (104, 'Logan Jackson', 30, 1, 'User 104 bio description', 44.56);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (105, 'Avery Davis', 27, 1, 'User 105 bio description', 10.5);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (106, 'Alex Wilson', 32, 0, 'User 106 bio description', 96.22);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (107, 'Quinn Anderson', 21, 1, 'User 107 bio description', 92.57);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (108, 'Alex Anderson', 26, 1, 'User 108 bio description', 70.08);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (109, 'Skyler Martin', 38, 1, 'User 109 bio description', 90.23);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (110, 'Hayden Taylor', 45, 1, 'User 110 bio description', 59.31);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (111, 'Taylor Thomas', 46, 0, 'User 111 bio description', 32.25);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (112, 'Chris Taylor', 49, 1, 'User 112 bio description', 34.71);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (113, 'Kiri Martinez', 33, 0, 'User 113 bio description', 38.77);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (114, 'Skyler Williams', 26, 0, 'User 114 bio description', 44.47);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (115, 'Jordan Miller', 22, 1, 'User 115 bio description', 39.78);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (116, 'Dakota Wilson', 21, 0, 'User 116 bio description', 47.81);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (117, 'Rowan Smith', 72, 1, 'User 117 bio description', 61.81);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (118, 'Reese Smith', 78, 1, 'User 118 bio description', 77.81);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (119, 'Logan Moore', 65, 1, 'User 119 bio description', 81.99);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (120, 'Sam Thomas', 32, 0, 'User 120 bio description', 53.71);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (121, 'Avery Hernandez', 60, 1, 'User 121 bio description', 46.39);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (122, 'Taylor Anderson', 76, 0, 'User 122 bio description', 66.0);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (123, 'Amatsagu Gonzalez', 55, 1, 'User 123 bio description', 12.44);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (124, 'Logan Jones', 73, 1, 'User 124 bio description', 14.53);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (125, 'Avery Hernandez', 31, 1, 'User 125 bio description', 40.38);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (126, 'Avery Rodriguez', 66, 1, 'User 126 bio description', 47.94);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (127, 'Kiri Thomas', 19, 1, 'User 127 bio description', 14.69);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (128, 'Casey Davis', 59, 0, 'User 128 bio description', 96.16);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (129, 'Betta Smith', 78, 0, 'User 129 bio description', 85.53);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (130, 'Hayden Jones', 33, 0, 'User 130 bio description', 70.25);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (131, 'Rowan Miller', 47, 1, 'User 131 bio description', 79.02);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (132, 'Taylor Martin', 56, 1, 'User 132 bio description', 74.65);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (133, 'Taylor Martinez', 24, 1, 'User 133 bio description', 93.6);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (134, 'Rowan Gonzalez', 43, 1, 'User 134 bio description', 27.85);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (135, 'Rowan Davis', 24, 1, 'User 135 bio description', 37.14);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (136, 'Hayden Brown', 68, 1, 'User 136 bio description', 80.44);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (137, 'Casey Moore', 45, 1, 'User 137 bio description', 16.21);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (138, 'Riley Smith', 72, 1, 'User 138 bio description', 54.12);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (139, 'Logan Lopez', 58, 1, 'User 139 bio description', 51.38);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (140, 'Jordan Wilson', 29, 1, 'User 140 bio description', 96.89);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (141, 'Chris Martin', 69, 1, 'User 141 bio description', 79.72);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (142, 'Dakota Wilson', 70, 1, 'User 142 bio description', 34.16);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (143, 'Sam Williams', 35, 1, 'User 143 bio description', 31.95);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (144, 'Dakota Jackson', 57, 1, 'User 144 bio description', 40.28);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (145, 'Reese Hernandez', 29, 1, 'User 145 bio description', 41.93);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (146, 'Chris Hernandez', 35, 1, 'User 146 bio description', 73.11);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (147, 'Chris Moore', 18, 1, 'User 147 bio description', 27.2);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (148, 'Sam Wilson', 49, 1, 'User 148 bio description', 31.63);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (149, 'Reese Thomas', 46, 1, 'User 149 bio description', 18.37);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (150, 'Sam Gonzalez', 62, 0, 'User 150 bio description', 69.76);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (151, 'Casey Thomas', 53, 1, 'User 151 bio description', 48.3);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (152, 'Skyler Hernandez', 40, 1, 'User 152 bio description', 34.38);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (153, 'Chris Davis', 25, 1, 'User 153 bio description', 38.4);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (154, 'Skyler Garcia', 30, 0, 'User 154 bio description', 53.58);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (155, 'Rowan Taylor', 56, 0, 'User 155 bio description', 19.05);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (156, 'Morgan Martinez', 32, 1, 'User 156 bio description', 37.2);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (157, 'Skyler Jones', 35, 0, 'User 157 bio description', 14.91);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (158, 'Pat Jones', 58, 1, 'User 158 bio description', 54.18);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (159, 'Amatsagu Jackson', 36, 1, 'User 159 bio description', 49.64);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (160, 'Taylor Johnson', 34, 1, 'User 160 bio description', 53.0);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (161, 'Kiri Gonzalez', 49, 0, 'User 161 bio description', 66.65);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (162, 'Betta Jones', 27, 1, 'User 162 bio description', 95.42);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (163, 'Kiri Davis', 25, 1, 'User 163 bio description', 47.46);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (164, 'Hayden Martin', 32, 1, 'User 164 bio description', 44.23);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (165, 'Dakota Martinez', 73, 1, 'User 165 bio description', 48.59);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (166, 'Rowan Martin', 21, 1, 'User 166 bio description', 76.61);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (167, 'Morgan Miller', 34, 1, 'User 167 bio description', 24.14);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (168, 'Taylor Moore', 22, 0, 'User 168 bio description', 46.77);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (169, 'Hayden Thomas', 36, 0, 'User 169 bio description', 35.93);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (170, 'Pat Anderson', 22, 1, 'User 170 bio description', 93.15);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (171, 'Rowan Miller', 45, 0, 'User 171 bio description', 30.23);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (172, 'Jordan Rodriguez', 70, 0, 'User 172 bio description', 15.37);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (173, 'Pat Martin', 65, 1, 'User 173 bio description', 92.91);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (174, 'Dakota Brown', 47, 1, 'User 174 bio description', 72.98);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (175, 'Chris Taylor', 52, 1, 'User 175 bio description', 17.24);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (176, 'Betta Wilson', 65, 1, 'User 176 bio description', 32.53);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (177, 'Kiri Davis', 79, 1, 'User 177 bio description', 87.45);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (178, 'Rowan Smith', 66, 1, 'User 178 bio description', 34.26);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (179, 'Betta Garcia', 48, 1, 'User 179 bio description', 49.8);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (180, 'Chris Garcia', 55, 1, 'User 180 bio description', 83.28);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (181, 'Kiri Thomas', 40, 1, 'User 181 bio description', 38.9);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (182, 'Alex Garcia', 39, 1, 'User 182 bio description', 54.59);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (183, 'Avery Moore', 20, 1, 'User 183 bio description', 38.31);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (184, 'Riley Brown', 80, 1, 'User 184 bio description', 87.84);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (185, 'Amatsagu Moore', 47, 1, 'User 185 bio description', 26.88);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (186, 'Casey Martin', 66, 1, 'User 186 bio description', 49.78);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (187, 'Betta Miller', 35, 1, 'User 187 bio description', 93.49);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (188, 'Dakota Thomas', 25, 0, 'User 188 bio description', 66.7);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (189, 'Sam Garcia', 37, 1, 'User 189 bio description', 59.7);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (190, 'Kiri Davis', 71, 1, 'User 190 bio description', 51.53);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (191, 'Alex Jones', 49, 1, 'User 191 bio description', 36.27);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (192, 'Chris Wilson', 71, 1, 'User 192 bio description', 52.5);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (193, 'Dakota Moore', 27, 1, 'User 193 bio description', 92.97);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (194, 'Quinn Jones', 73, 0, 'User 194 bio description', 79.54);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (195, 'Logan Hernandez', 77, 1, 'User 195 bio description', 34.05);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (196, 'Amatsagu Martinez', 64, 0, 'User 196 bio description', 62.82);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (197, 'Reese Jones', 46, 1, 'User 197 bio description', 41.06);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (198, 'Skyler Moore', 42, 1, 'User 198 bio description', 38.96);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (199, 'Morgan Davis', 54, 1, 'User 199 bio description', 87.04);
INSERT INTO users (id, surname, age, active, bio, score) VALUES (200, 'Logan Johnson', 38, 1, 'User 200 bio description', 73.47);
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0001', 'Max Tire 1', 344, 811, 'Home');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0002', 'Lite Phone 2', 69, 514, 'Health');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0003', 'Pro Book 3', 452, 865, 'Clothing');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0004', 'Super Snack 4', 471, 467, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0005', 'Eco Tire 5', 450, 670, 'Home');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0006', 'Super Shirt 6', 405, 992, 'Toys');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0007', 'Pro Cream 7', 359, 407, 'Books');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0008', 'Pro Snack 8', 199, 977, 'Sports');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0009', 'Lite Snack 9', 23, 632, 'Books');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0010', 'Smart Drone 10', 121, 764, 'Books');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0011', 'Max Book 11', 394, 648, 'Books');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0012', 'Lite Chair 12', 360, 306, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0013', 'Ultra Watch 13', 412, 57, 'Toys');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0014', 'Pro Watch 14', 225, 149, 'Garden');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0015', 'Prime Tire 15', 294, 698, 'Home');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0016', 'Eco Chair 16', 45, 624, 'Automotive');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0017', 'Core Hose 17', 259, 934, 'Health');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0018', 'Eco Hose 18', 241, 653, 'Toys');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0019', 'Lite Drone 19', 346, 9, 'Clothing');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0020', 'Mega Snack 20', 85, 75, 'Clothing');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0021', 'Pro Cream 21', 158, 654, 'Automotive');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0022', 'Mega Shirt 22', 437, 309, 'Garden');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0023', 'Max Shirt 23', 59, 242, 'Automotive');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0024', 'Core Watch 24', 299, 302, 'Toys');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0025', 'Ultra Tire 25', 145, 8, 'Health');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0026', 'Ultra Cream 26', 386, 508, 'Toys');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0027', 'Smart Cream 27', 415, 360, 'Garden');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0028', 'Smart Cream 28', 133, 694, 'Home');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0029', 'Super Phone 29', 163, 807, 'Clothing');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0030', 'Ultra Cream 30', 191, 749, 'Home');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0031', 'Super Drone 31', 172, 765, 'Automotive');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0032', 'Eco Hose 32', 72, 805, 'Food');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0033', 'Pro Snack 33', 261, 935, 'Toys');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0034', 'Eco Drone 34', 472, 844, 'Clothing');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0035', 'Mega Watch 35', 416, 117, 'Clothing');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0036', 'Super Chair 36', 391, 989, 'Garden');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0037', 'Max Snack 37', 192, 92, 'Automotive');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0038', 'Ultra Drone 38', 279, 126, 'Clothing');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0039', 'Pro Drone 39', 304, 390, 'Sports');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0040', 'Super Hose 40', 246, 25, 'Health');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0041', 'Prime Watch 41', 473, 624, 'Garden');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0042', 'Super Shirt 42', 470, 717, 'Toys');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0043', 'Max Book 43', 76, 46, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0044', 'Mega Shirt 44', 64, 99, 'Garden');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0045', 'Prime Chair 45', 203, 464, 'Sports');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0046', 'Prime Tire 46', 305, 760, 'Home');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0047', 'Max Book 47', 431, 501, 'Health');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0048', 'Max Drone 48', 21, 706, 'Sports');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0049', 'Smart Shirt 49', 232, 973, 'Garden');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0050', 'Pro Book 50', 356, 376, 'Food');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0051', 'Pro Phone 51', 208, 282, 'Garden');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0052', 'Super Shirt 52', 51, 678, 'Garden');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0053', 'Core Phone 53', 30, 805, 'Sports');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0054', 'Smart Chair 54', 407, 578, 'Garden');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0055', 'Super Snack 55', 111, 600, 'Garden');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0056', 'Smart Watch 56', 401, 151, 'Health');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0057', 'Ultra Drone 57', 444, 148, 'Home');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0058', 'Prime Drone 58', 413, 178, 'Books');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0059', 'Ultra Chair 59', 12, 366, 'Garden');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0060', 'Core Watch 60', 13, 178, 'Toys');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0061', 'Ultra Chair 61', 384, 431, 'Food');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0062', 'Super Book 62', 248, 459, 'Sports');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0063', 'Prime Cream 63', 60, 462, 'Food');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0064', 'Smart Cream 64', 27, 744, 'Food');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0065', 'Mega Shirt 65', 334, 987, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0066', 'Ultra Shirt 66', 438, 411, 'Automotive');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0067', 'Super Shirt 67', 369, 931, 'Clothing');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0068', 'Super Book 68', 169, 622, 'Home');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0069', 'Super Chair 69', 145, 639, 'Health');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0070', 'Prime Watch 70', 200, 611, 'Food');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0071', 'Mega Shirt 71', 263, 619, 'Automotive');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0072', 'Super Book 72', 441, 670, 'Food');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0073', 'Smart Tire 73', 236, 909, 'Garden');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0074', 'Max Watch 74', 428, 464, 'Automotive');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0075', 'Max Book 75', 165, 437, 'Sports');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0076', 'Mega Watch 76', 493, 156, 'Clothing');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0077', 'Super Book 77', 430, 87, 'Books');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0078', 'Max Book 78', 386, 756, 'Sports');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0079', 'Eco Snack 79', 35, 600, 'Food');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0080', 'Prime Watch 80', 348, 125, 'Automotive');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0081', 'Pro Tire 81', 449, 937, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0082', 'Mega Cream 82', 164, 360, 'Books');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0083', 'Core Snack 83', 113, 158, 'Clothing');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0084', 'Smart Book 84', 184, 865, 'Food');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0085', 'Pro Book 85', 395, 285, 'Health');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0086', 'Smart Tire 86', 437, 574, 'Health');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0087', 'Core Snack 87', 18, 623, 'Toys');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0088', 'Ultra Chair 88', 144, 719, 'Toys');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0089', 'Pro Watch 89', 8, 185, 'Home');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0090', 'Core Tire 90', 40, 145, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0091', 'Super Snack 91', 115, 385, 'Automotive');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0092', 'Lite Watch 92', 85, 378, 'Toys');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0093', 'Pro Cream 93', 310, 86, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0094', 'Eco Chair 94', 391, 632, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0095', 'Super Drone 95', 231, 677, 'Automotive');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0096', 'Lite Cream 96', 231, 424, 'Toys');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0097', 'Smart Snack 97', 63, 353, 'Automotive');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0098', 'Super Drone 98', 352, 694, 'Health');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0099', 'Lite Snack 99', 346, 315, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0100', 'Smart Tire 100', 311, 56, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0101', 'Smart Drone 101', 489, 216, 'Home');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0102', 'Mega Drone 102', 172, 122, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0103', 'Lite Tire 103', 94, 132, 'Automotive');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0104', 'Prime Hose 104', 261, 572, 'Sports');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0105', 'Super Tire 105', 446, 759, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0106', 'Max Phone 106', 240, 943, 'Books');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0107', 'Pro Cream 107', 224, 587, 'Automotive');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0108', 'Max Drone 108', 63, 414, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0109', 'Pro Chair 109', 415, 970, 'Health');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0110', 'Lite Watch 110', 50, 447, 'Books');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0111', 'Smart Tire 111', 306, 410, 'Food');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0112', 'Super Tire 112', 450, 317, 'Sports');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0113', 'Smart Watch 113', 403, 172, 'Books');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0114', 'Prime Book 114', 276, 522, 'Garden');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0115', 'Pro Watch 115', 377, 981, 'Home');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0116', 'Smart Book 116', 79, 262, 'Garden');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0117', 'Eco Cream 117', 83, 778, 'Books');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0118', 'Eco Shirt 118', 242, 772, 'Health');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0119', 'Core Shirt 119', 353, 946, 'Health');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0120', 'Core Watch 120', 447, 994, 'Sports');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0121', 'Eco Shirt 121', 39, 480, 'Clothing');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0122', 'Mega Drone 122', 307, 57, 'Sports');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0123', 'Prime Book 123', 163, 472, 'Clothing');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0124', 'Ultra Phone 124', 193, 851, 'Toys');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0125', 'Super Book 125', 319, 608, 'Food');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0126', 'Max Shirt 126', 302, 567, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0127', 'Lite Cream 127', 338, 192, 'Sports');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0128', 'Core Shirt 128', 261, 154, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0129', 'Lite Book 129', 420, 920, 'Sports');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0130', 'Super Snack 130', 335, 176, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0131', 'Smart Shirt 131', 229, 536, 'Food');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0132', 'Core Chair 132', 191, 381, 'Toys');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0133', 'Max Tire 133', 401, 346, 'Health');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0134', 'Ultra Watch 134', 38, 337, 'Books');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0135', 'Prime Tire 135', 150, 258, 'Health');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0136', 'Eco Watch 136', 46, 596, 'Home');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0137', 'Pro Drone 137', 500, 671, 'Automotive');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0138', 'Eco Cream 138', 367, 960, 'Books');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0139', 'Mega Snack 139', 197, 658, 'Sports');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0140', 'Eco Snack 140', 52, 661, 'Automotive');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0141', 'Prime Watch 141', 14, 371, 'Toys');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0142', 'Eco Hose 142', 179, 970, 'Clothing');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0143', 'Smart Hose 143', 75, 158, 'Books');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0144', 'Mega Book 144', 264, 789, 'Food');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0145', 'Prime Phone 145', 343, 344, 'Health');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0146', 'Eco Cream 146', 197, 157, 'Home');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0147', 'Eco Cream 147', 419, 924, 'Home');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0148', 'Lite Phone 148', 215, 373, 'Garden');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0149', 'Lite Cream 149', 150, 770, 'Clothing');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0150', 'Smart Snack 150', 127, 316, 'Clothing');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0151', 'Smart Watch 151', 352, 969, 'Health');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0152', 'Lite Shirt 152', 398, 288, 'Automotive');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0153', 'Prime Snack 153', 219, 989, 'Home');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0154', 'Smart Cream 154', 75, 893, 'Toys');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0155', 'Ultra Shirt 155', 452, 380, 'Food');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0156', 'Super Snack 156', 440, 127, 'Toys');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0157', 'Super Chair 157', 144, 460, 'Food');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0158', 'Eco Tire 158', 51, 969, 'Garden');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0159', 'Lite Watch 159', 481, 27, 'Automotive');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0160', 'Ultra Tire 160', 262, 382, 'Garden');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0161', 'Max Book 161', 196, 229, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0162', 'Pro Book 162', 434, 731, 'Sports');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0163', 'Eco Chair 163', 24, 293, 'Clothing');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0164', 'Eco Shirt 164', 234, 630, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0165', 'Super Phone 165', 136, 220, 'Home');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0166', 'Prime Cream 166', 275, 433, 'Books');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0167', 'Mega Hose 167', 159, 124, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0168', 'Smart Tire 168', 332, 812, 'Health');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0169', 'Lite Book 169', 61, 856, 'Clothing');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0170', 'Core Snack 170', 13, 647, 'Food');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0171', 'Core Hose 171', 372, 147, 'Toys');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0172', 'Max Phone 172', 319, 361, 'Garden');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0173', 'Core Tire 173', 100, 680, 'Books');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0174', 'Prime Watch 174', 39, 976, 'Food');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0175', 'Prime Snack 175', 407, 519, 'Food');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0176', 'Ultra Tire 176', 452, 481, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0177', 'Max Watch 177', 134, 765, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0178', 'Pro Book 178', 181, 246, 'Books');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0179', 'Core Watch 179', 73, 45, 'Sports');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0180', 'Prime Watch 180', 421, 658, 'Home');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0181', 'Lite Shirt 181', 328, 186, 'Home');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0182', 'Super Shirt 182', 23, 300, 'Garden');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0183', 'Ultra Hose 183', 458, 42, 'Sports');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0184', 'Mega Snack 184', 208, 834, 'Food');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0185', 'Lite Drone 185', 23, 771, 'Garden');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0186', 'Mega Watch 186', 446, 799, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0187', 'Pro Drone 187', 68, 818, 'Sports');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0188', 'Max Tire 188', 385, 450, 'Automotive');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0189', 'Pro Chair 189', 259, 708, 'Clothing');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0190', 'Pro Snack 190', 141, 820, 'Books');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0191', 'Max Book 191', 225, 616, 'Home');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0192', 'Prime Drone 192', 169, 105, 'Books');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0193', 'Pro Drone 193', 161, 456, 'Health');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0194', 'Max Chair 194', 358, 454, 'Sports');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0195', 'Lite Phone 195', 377, 890, 'Sports');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0196', 'Core Tire 196', 145, 654, 'Electronics');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0197', 'Super Tire 197', 191, 525, 'Home');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0198', 'Ultra Chair 198', 439, 622, 'Clothing');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0199', 'Ultra Chair 199', 39, 241, 'Sports');
INSERT INTO products (sku, name, price, stock, category) VALUES ('SKU-0200', 'Pro Tire 200', 491, 580, 'Electronics');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (1, 1, 10, 119.05, 'cancelled');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (1, 2, 6, 130.44, 'pending');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (2, 1, 10, 111.96, 'shipped');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (2, 2, 7, 134.03, 'shipped');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (3, 1, 4, 192.89, 'pending');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (3, 2, 3, 82.37, 'cancelled');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (4, 1, 9, 92.69, 'shipped');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (4, 2, 8, 117.25, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (5, 1, 5, 181.15, 'cancelled');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (5, 2, 4, 42.07, 'pending');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (6, 1, 8, 102.16, 'cancelled');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (6, 2, 2, 82.95, 'shipped');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (7, 1, 6, 221.58, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (7, 2, 9, 162.6, 'shipped');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (8, 1, 3, 111.09, 'completed');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (8, 2, 6, 167.36, 'pending');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (9, 1, 4, 162.57, 'completed');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (9, 2, 8, 49.46, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (10, 1, 10, 216.01, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (10, 2, 3, 97.61, 'pending');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (11, 1, 2, 37.84, 'cancelled');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (11, 2, 9, 211.37, 'cancelled');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (12, 1, 10, 83.19, 'shipped');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (12, 2, 2, 50.5, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (13, 1, 6, 64.65, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (13, 2, 10, 131.88, 'completed');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (14, 1, 7, 193.4, 'pending');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (14, 2, 2, 56.63, 'shipped');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (15, 1, 3, 36.87, 'completed');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (15, 2, 6, 285.82, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (16, 1, 5, 215.34, 'shipped');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (16, 2, 4, 134.31, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (17, 1, 5, 53.16, 'shipped');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (17, 2, 10, 290.07, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (18, 1, 3, 94.89, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (18, 2, 3, 38.11, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (19, 1, 10, 201.93, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (19, 2, 1, 42.14, 'pending');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (20, 1, 2, 14.09, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (20, 2, 5, 171.5, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (21, 1, 7, 229.7, 'pending');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (21, 2, 8, 360.04, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (22, 1, 5, 169.43, 'shipped');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (22, 2, 8, 128.16, 'cancelled');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (23, 1, 5, 127.05, 'pending');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (23, 2, 3, 74.35, 'cancelled');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (24, 1, 8, 113.45, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (24, 2, 3, 57.2, 'shipped');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (25, 1, 6, 293.35, 'completed');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (25, 2, 6, 169.04, 'pending');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (26, 1, 6, 95.27, 'pending');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (26, 2, 5, 126.16, 'completed');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (27, 1, 2, 14.55, 'cancelled');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (27, 2, 10, 238.16, 'completed');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (28, 1, 6, 282.11, 'shipped');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (28, 2, 4, 157.36, 'cancelled');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (29, 1, 9, 234.06, 'shipped');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (29, 2, 8, 48.34, 'cancelled');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (30, 1, 9, 230.18, 'completed');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (30, 2, 4, 125.0, 'pending');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (31, 1, 1, 17.66, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (31, 2, 8, 142.87, 'pending');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (32, 1, 2, 48.78, 'shipped');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (32, 2, 6, 236.24, 'shipped');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (33, 1, 1, 23.03, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (33, 2, 9, 123.84, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (34, 1, 5, 41.54, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (34, 2, 8, 315.19, 'shipped');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (35, 1, 10, 356.18, 'pending');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (35, 2, 3, 146.64, 'cancelled');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (36, 1, 6, 244.62, 'shipped');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (36, 2, 9, 425.27, 'completed');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (37, 1, 4, 128.44, 'cancelled');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (37, 2, 9, 61.3, 'pending');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (38, 1, 3, 111.33, 'cancelled');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (38, 2, 9, 230.08, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (39, 1, 9, 101.61, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (39, 2, 6, 73.88, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (40, 1, 5, 158.59, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (40, 2, 9, 260.6, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (41, 1, 5, 131.85, 'pending');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (41, 2, 6, 119.43, 'pending');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (42, 1, 7, 218.87, 'pending');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (42, 2, 10, 263.57, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (43, 1, 10, 152.39, 'pending');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (43, 2, 10, 266.2, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (44, 1, 10, 398.57, 'cancelled');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (44, 2, 3, 125.92, 'completed');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (45, 1, 1, 30.77, 'pending');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (45, 2, 4, 23.41, 'shipped');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (46, 1, 7, 82.7, 'completed');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (46, 2, 7, 193.07, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (47, 1, 8, 354.21, 'pending');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (47, 2, 3, 85.02, 'processing');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (48, 1, 6, 299.49, 'cancelled');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (48, 2, 9, 197.61, 'completed');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (49, 1, 8, 368.36, 'shipped');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (49, 2, 9, 188.49, 'shipped');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (50, 1, 10, 267.88, 'completed');
INSERT INTO orders (order_id, item_id, quantity, total, status) VALUES (50, 2, 5, 150.57, 'completed');
